/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardAdminArticlesRouteImport } from './routes/_dashboard/admin/articles'
import { Route as DashboardAdminCommentsRouteImport } from './routes/_dashboard/admin/comments'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/_dashboard/admin/payments'
import { Route as DashboardAdminSettingsRouteImport } from './routes/_dashboard/admin/settings'
import { Route as DashboardAdminSubscribersRouteImport } from './routes/_dashboard/admin/subscribers'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthSignupRouteImport } from './routes/_public/auth/signup'
import { Route as PublicAuthVerifyOtpRouteImport } from './routes/_public/auth/verify-otp'
import { Route as PublicDemoBetterAuthRouteImport } from './routes/_public/demo/better-auth'
import { Route as PublicDemoPrismaRouteImport } from './routes/_public/demo/prisma'
import { Route as PublicDemoStrapiRouteImport } from './routes/_public/demo/strapi'
import { Route as PublicDemoTableRouteImport } from './routes/_public/demo/table'
import { Route as PublicDemoTanstackQueryRouteImport } from './routes/_public/demo/tanstack-query'
import { Route as PublicPostsIndexRouteImport } from './routes/_public/posts/index'
import { Route as PublicPostsPostIdRouteImport } from './routes/_public/posts/$postId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicDemoFormAddressRouteImport } from './routes/_public/demo/form.address'
import { Route as PublicDemoFormSimpleRouteImport } from './routes/_public/demo/form.simple'
import { Route as PublicDemoSentryTestingRouteImport } from './routes/_public/demo/sentry.testing'
import { Route as PublicDemoStrapiArticleIdRouteImport } from './routes/_public/demo/strapi.$articleId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminArticlesRoute = DashboardAdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCommentsRoute = DashboardAdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSubscribersRoute =
  DashboardAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => DashboardRoute,
  } as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthSignupRoute = PublicAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthVerifyOtpRoute = PublicAuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoBetterAuthRoute = PublicDemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoPrismaRoute = PublicDemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoStrapiRoute = PublicDemoStrapiRouteImport.update({
  id: '/demo/strapi',
  path: '/demo/strapi',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoTableRoute = PublicDemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoTanstackQueryRoute = PublicDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostsIndexRoute = PublicPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostsPostIdRoute = PublicPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDemoFormAddressRoute = PublicDemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoFormSimpleRoute = PublicDemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoSentryTestingRoute = PublicDemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoStrapiArticleIdRoute =
  PublicDemoStrapiArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => PublicDemoStrapiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/api/inngest': typeof ApiInngestRoute
  '/admin/articles': typeof DashboardAdminArticlesRoute
  '/admin/comments': typeof DashboardAdminCommentsRoute
  '/admin/payments': typeof DashboardAdminPaymentsRoute
  '/admin/settings': typeof DashboardAdminSettingsRoute
  '/admin/subscribers': typeof DashboardAdminSubscribersRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/signup': typeof PublicAuthSignupRoute
  '/auth/verify-otp': typeof PublicAuthVerifyOtpRoute
  '/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/demo/prisma': typeof PublicDemoPrismaRoute
  '/demo/strapi': typeof PublicDemoStrapiRouteWithChildren
  '/demo/table': typeof PublicDemoTableRoute
  '/demo/tanstack-query': typeof PublicDemoTanstackQueryRoute
  '/posts/$postId': typeof PublicPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/posts/': typeof PublicPostsIndexRoute
  '/demo/form/address': typeof PublicDemoFormAddressRoute
  '/demo/form/simple': typeof PublicDemoFormSimpleRoute
  '/demo/sentry/testing': typeof PublicDemoSentryTestingRoute
  '/demo/strapi/$articleId': typeof PublicDemoStrapiArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/api/inngest': typeof ApiInngestRoute
  '/admin/articles': typeof DashboardAdminArticlesRoute
  '/admin/comments': typeof DashboardAdminCommentsRoute
  '/admin/payments': typeof DashboardAdminPaymentsRoute
  '/admin/settings': typeof DashboardAdminSettingsRoute
  '/admin/subscribers': typeof DashboardAdminSubscribersRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/signup': typeof PublicAuthSignupRoute
  '/auth/verify-otp': typeof PublicAuthVerifyOtpRoute
  '/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/demo/prisma': typeof PublicDemoPrismaRoute
  '/demo/strapi': typeof PublicDemoStrapiRouteWithChildren
  '/demo/table': typeof PublicDemoTableRoute
  '/demo/tanstack-query': typeof PublicDemoTanstackQueryRoute
  '/posts/$postId': typeof PublicPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/posts': typeof PublicPostsIndexRoute
  '/demo/form/address': typeof PublicDemoFormAddressRoute
  '/demo/form/simple': typeof PublicDemoFormSimpleRoute
  '/demo/sentry/testing': typeof PublicDemoSentryTestingRoute
  '/demo/strapi/$articleId': typeof PublicDemoStrapiArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_public/': typeof PublicIndexRoute
  '/_dashboard/admin/articles': typeof DashboardAdminArticlesRoute
  '/_dashboard/admin/comments': typeof DashboardAdminCommentsRoute
  '/_dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/_dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/_dashboard/admin/subscribers': typeof DashboardAdminSubscribersRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/signup': typeof PublicAuthSignupRoute
  '/_public/auth/verify-otp': typeof PublicAuthVerifyOtpRoute
  '/_public/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/_public/demo/prisma': typeof PublicDemoPrismaRoute
  '/_public/demo/strapi': typeof PublicDemoStrapiRouteWithChildren
  '/_public/demo/table': typeof PublicDemoTableRoute
  '/_public/demo/tanstack-query': typeof PublicDemoTanstackQueryRoute
  '/_public/posts/$postId': typeof PublicPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_public/posts/': typeof PublicPostsIndexRoute
  '/_public/demo/form/address': typeof PublicDemoFormAddressRoute
  '/_public/demo/form/simple': typeof PublicDemoFormSimpleRoute
  '/_public/demo/sentry/testing': typeof PublicDemoSentryTestingRoute
  '/_public/demo/strapi/$articleId': typeof PublicDemoStrapiArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/inngest'
    | '/admin/articles'
    | '/admin/comments'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/demo/better-auth'
    | '/demo/prisma'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/admin/'
    | '/posts/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/strapi/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/inngest'
    | '/admin/articles'
    | '/admin/comments'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/demo/better-auth'
    | '/demo/prisma'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/admin'
    | '/posts'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/strapi/$articleId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_public'
    | '/_public/about'
    | '/api/inngest'
    | '/_public/'
    | '/_dashboard/admin/articles'
    | '/_dashboard/admin/comments'
    | '/_dashboard/admin/payments'
    | '/_dashboard/admin/settings'
    | '/_dashboard/admin/subscribers'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/signup'
    | '/_public/auth/verify-otp'
    | '/_public/demo/better-auth'
    | '/_public/demo/prisma'
    | '/_public/demo/strapi'
    | '/_public/demo/table'
    | '/_public/demo/tanstack-query'
    | '/_public/posts/$postId'
    | '/api/auth/$'
    | '/_dashboard/admin/'
    | '/_public/posts/'
    | '/_public/demo/form/address'
    | '/_public/demo/form/simple'
    | '/_public/demo/sentry/testing'
    | '/_public/demo/strapi/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/articles': {
      id: '/_dashboard/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof DashboardAdminArticlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/comments': {
      id: '/_dashboard/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof DashboardAdminCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/payments': {
      id: '/_dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/settings': {
      id: '/_dashboard/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/subscribers': {
      id: '/_dashboard/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof DashboardAdminSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/signup': {
      id: '/_public/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof PublicAuthSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/verify-otp': {
      id: '/_public/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof PublicAuthVerifyOtpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/better-auth': {
      id: '/_public/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof PublicDemoBetterAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/prisma': {
      id: '/_public/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof PublicDemoPrismaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/strapi': {
      id: '/_public/demo/strapi'
      path: '/demo/strapi'
      fullPath: '/demo/strapi'
      preLoaderRoute: typeof PublicDemoStrapiRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/table': {
      id: '/_public/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof PublicDemoTableRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/tanstack-query': {
      id: '/_public/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof PublicDemoTanstackQueryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts/': {
      id: '/_public/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicPostsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/posts/$postId': {
      id: '/_public/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PublicPostsPostIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/demo/form/address': {
      id: '/_public/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof PublicDemoFormAddressRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/form/simple': {
      id: '/_public/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof PublicDemoFormSimpleRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/sentry/testing': {
      id: '/_public/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof PublicDemoSentryTestingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo/strapi/$articleId': {
      id: '/_public/demo/strapi/$articleId'
      path: '/$articleId'
      fullPath: '/demo/strapi/$articleId'
      preLoaderRoute: typeof PublicDemoStrapiArticleIdRouteImport
      parentRoute: typeof PublicDemoStrapiRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminArticlesRoute: typeof DashboardAdminArticlesRoute
  DashboardAdminCommentsRoute: typeof DashboardAdminCommentsRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminSubscribersRoute: typeof DashboardAdminSubscribersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminArticlesRoute: DashboardAdminArticlesRoute,
  DashboardAdminCommentsRoute: DashboardAdminCommentsRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminSubscribersRoute: DashboardAdminSubscribersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicDemoStrapiRouteChildren {
  PublicDemoStrapiArticleIdRoute: typeof PublicDemoStrapiArticleIdRoute
}

const PublicDemoStrapiRouteChildren: PublicDemoStrapiRouteChildren = {
  PublicDemoStrapiArticleIdRoute: PublicDemoStrapiArticleIdRoute,
}

const PublicDemoStrapiRouteWithChildren =
  PublicDemoStrapiRoute._addFileChildren(PublicDemoStrapiRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthSignupRoute: typeof PublicAuthSignupRoute
  PublicAuthVerifyOtpRoute: typeof PublicAuthVerifyOtpRoute
  PublicDemoBetterAuthRoute: typeof PublicDemoBetterAuthRoute
  PublicDemoPrismaRoute: typeof PublicDemoPrismaRoute
  PublicDemoStrapiRoute: typeof PublicDemoStrapiRouteWithChildren
  PublicDemoTableRoute: typeof PublicDemoTableRoute
  PublicDemoTanstackQueryRoute: typeof PublicDemoTanstackQueryRoute
  PublicPostsPostIdRoute: typeof PublicPostsPostIdRoute
  PublicPostsIndexRoute: typeof PublicPostsIndexRoute
  PublicDemoFormAddressRoute: typeof PublicDemoFormAddressRoute
  PublicDemoFormSimpleRoute: typeof PublicDemoFormSimpleRoute
  PublicDemoSentryTestingRoute: typeof PublicDemoSentryTestingRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthSignupRoute: PublicAuthSignupRoute,
  PublicAuthVerifyOtpRoute: PublicAuthVerifyOtpRoute,
  PublicDemoBetterAuthRoute: PublicDemoBetterAuthRoute,
  PublicDemoPrismaRoute: PublicDemoPrismaRoute,
  PublicDemoStrapiRoute: PublicDemoStrapiRouteWithChildren,
  PublicDemoTableRoute: PublicDemoTableRoute,
  PublicDemoTanstackQueryRoute: PublicDemoTanstackQueryRoute,
  PublicPostsPostIdRoute: PublicPostsPostIdRoute,
  PublicPostsIndexRoute: PublicPostsIndexRoute,
  PublicDemoFormAddressRoute: PublicDemoFormAddressRoute,
  PublicDemoFormSimpleRoute: PublicDemoFormSimpleRoute,
  PublicDemoSentryTestingRoute: PublicDemoSentryTestingRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
